/**
 * The Speaker for a provider, a key and a collaborator's settings.
 *
 * One place that knows every provider, so a route and the worker cannot build them
 * differently: a line regenerated by hand and the same line in a batch must be made alike.
 */
import "server-only";

import type { Preference } from "../preference";
import { elevenLabsSpeaker } from "./elevenlabs";
import { fishSpeaker } from "./fish";
import type { Provider, Speaker } from "./speaker";

export function speakerFrom(
  provider: Provider,
  apiKey: string,
  preference: Pick<Preference, "elevenlabs" | "fish">,
): Speaker {
  return provider === "fish"
    ? fishSpeaker({ apiKey, settings: preference.fish })
    : elevenLabsSpeaker({ apiKey, settings: preference.elevenlabs });
}
