/**
 * The Speaker for a provider, a key and a collaborator's fish.audio settings.
 *
 * One place that knows every provider, so a route and the worker cannot build them
 * differently: a line regenerated by hand and the same line in a batch must be made alike.
 */
import "server-only";

import type { FishSettings } from "../fish-tts";
import { elevenLabsSpeaker } from "./elevenlabs";
import { fishSpeaker } from "./fish";
import type { Provider, Speaker } from "./speaker";

export function speakerFrom(provider: Provider, apiKey: string, fish: FishSettings): Speaker {
  return provider === "fish"
    ? fishSpeaker({ apiKey, settings: fish })
    : elevenLabsSpeaker({ apiKey });
}
