// The sound pack's table: which clip narrates which page, and how long it runs.
//
// A module rather than a script, because two callers need it. `make books-lookup` runs it
// by hand after a batch; the site runs it when the regeneration queue drains, so a take
// somebody generated in the explorer reaches the addon without anyone remembering to
// rebuild anything. lib/zones/tools.ts imports its equivalent for exactly the same reason.
//
// Durations are recorded at generation time because the client cannot report the length of
// a sound file, and without them the player's Play button never resets itself.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import pg from "pg";

const ROOT = new URL("../../../../", import.meta.url).pathname;
const LANG = "enUS";

/**
 * Where a language's table is written: English's beside its clips in the pack folder, which is
 * committed and zipped in place; another language's in its work area under build/, which
 * scripts/books/package-audio.sh stages a pack from.
 */
export function lookupPath(lang) {
  return lang === LANG
    ? join(ROOT, "addons/SpokenBooksAudio/Data/Sounds.lua")
    : join(ROOT, "build/books", lang, "Data/Sounds.lua");
}

const HEADER = `-- AUTO-GENERATED by pipelines/books/tools/lib/lookup.mjs. Do not edit by hand.
--
-- Durations are recorded at generation time because the client cannot report how long a
-- sound file is; without them the Play button never resets itself.
--
-- A page with no clip is simply absent. There is no stand-in: substituting unrelated audio
-- is worse than silence, because silence is honest about what is missing.
--
-- Globals rather than a private namespace: a data addon cannot reach into SpokenBooks's.
-- Regenerate with:  make books-lookup`;

/**
 * Writes Data/Sounds.lua from the current takes. Returns what it wrote.
 *
 * @param options.lang which language's takes, defaulting to English
 * @param options.out an explicit path, for tests
 */
export async function buildLookup({ lang = LANG, out = lookupPath(lang) } = {}) {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set -- the takes live in Postgres");

  const pool = new pg.Pool({ connectionString: url });
  try {
    // Joined to the corpus rather than trusting the take's lineId: a take for a page no
    // longer in the corpus has nothing to narrate, and an entry for it would be a row the
    // addon can never reach.
    const { rows } = await pool.query(
      `select b."pageId", t."file", t."durationSec"
         from "take" t
         join "book_line" b
           on b."lineId" = t."lineId" and b."lang" = t."lang" and b."isCurrent"
        where t."source" = 'books' and t."isCurrent" and t."lang" = $1
        order by b."pageId"`,
      [lang],
    );

    const lines = [
      HEADER,
      "",
      "local ADDON_NAME = ...",
      "",
      "local pack = {",
      "\tversion = 1,",
      "\taddon = ADDON_NAME,",
      '\tquality = "high",',
      "\tbitrate = 128,",
      `\tlanguage = "${lang}",`,
      "\tpages = {",
    ];

    for (const row of rows) {
      // Null only for a take imported from a store this app did not cut. Written as 0 so
      // the addon can tell "unknown" from "short" and fall back to its own timer.
      const len = row.durationSec === null ? 0 : row.durationSec;
      lines.push(`\t\t[${row.pageId}] = { file = "${row.file}", len = ${len} },`);
    }

    lines.push(
      "\t},",
      "}",
      "",
      "SpokenBooksAudioPacks = SpokenBooksAudioPacks or {}",
      "SpokenBooksAudioPacks[ADDON_NAME] = pack",
      "",
    );

    await mkdir(dirname(out), { recursive: true });
    await writeFile(out, lines.join("\n"));

    return { clips: rows.length, path: out };
  } finally {
    await pool.end();
  }
}
