// The sound pack's table: which clip narrates which page, and how long it runs.
//
// A module rather than a script, because two callers need it. `make books-lookup` runs it
// by hand after a batch; the site runs it when the regeneration queue drains, so a take
// somebody generated in the explorer reaches the addon without anyone remembering to
// rebuild anything. lib/zones/tools.ts imports its equivalent for exactly the same reason.
//
// Durations are recorded at generation time because the client cannot report the length of
// a sound file, and without them the player's Play button never resets itself.
//
// A language's pack also carries that language's page index. The English one, in the
// SpokenBooks addon, is keyed on the English title and a checksum of the English words, and a
// client in another locale shows neither: without its own index a translated page is never
// found at all. It ships in the pack because a client in that locale is the only one it can
// match, and a player there who wants the language installs the pack.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import pg from "pg";

import { indexLua, pageIndex } from "./lua.mjs";

const ROOT = new URL("../../../../", import.meta.url).pathname;
const LANG = "enUS";

/**
 * Where a language's table is written: English's beside its clips in the pack folder, which is
 * committed and zipped in place; another language's in its work area under build/, which
 * scripts/books/package-audio.sh stages a pack from.
 */
export function lookupPath(lang) {
  return lang === LANG
    ? join(ROOT, "addons/SpokenBooksAudio/Data/Sounds.lua")
    : join(ROOT, "build/books", lang, "Data/Sounds.lua");
}

const HEADER = `-- AUTO-GENERATED by pipelines/books/tools/lib/lookup.mjs. Do not edit by hand.
--
-- Durations are recorded at generation time because the client cannot report how long a
-- sound file is; without them the Play button never resets itself.
--
-- A page with no clip is simply absent. There is no stand-in: substituting unrelated audio
-- is worse than silence, because silence is honest about what is missing.
--
-- Globals rather than a private namespace: a data addon cannot reach into SpokenBooks's.
-- Regenerate with:  make books-lookup`;

/**
 * The index entries for a language's pages: each page under every name its owners have in that
 * language, which is what ItemTextGetItem returns on that client.
 *
 * @param pages `{ pageId, bookId, pageNumber, ownerKind, ownerIds, text }`, text being the
 *   page as the client shows it
 * @param names `{ kind, entityId, name }` in that language, kind as entity_name spells it
 */
export function localeEntries(pages, names) {
  const byOwner = new Map(names.map((row) => [`${row.kind}:${row.entityId}`, row.name]));
  return pages.map((page) => {
    const kind = page.ownerKind === "object" ? "gameobject" : "item";
    const titles = [...new Set(page.ownerIds.map((id) => byOwner.get(`${kind}:${id}`)).filter(Boolean))];
    return { ...page, titles: titles.sort() };
  });
}

/**
 * Data/Sounds.lua for a pack.
 *
 * @param lang the language the clips are recorded in
 * @param clips `{ pageId, file, durationSec }`, in page order
 * @param entries a language's localeEntries, or null for English, whose index is the addon's
 */
export function packLua(lang, clips, entries = null) {
  const lines = [
    HEADER,
    "",
    "local ADDON_NAME = ...",
    "",
    "local pack = {",
    "\tversion = 1,",
    "\taddon = ADDON_NAME,",
    '\tquality = "high",',
    "\tbitrate = 128,",
    `\tlanguage = "${lang}",`,
    "\tpages = {",
  ];

  for (const row of clips) {
    // Null only for a take imported from a store this app did not cut. Written as 0 so
    // the addon can tell "unknown" from "short" and fall back to its own timer.
    const len = row.durationSec === null ? 0 : row.durationSec;
    lines.push(`\t\t[${row.pageId}] = { file = "${row.file}", len = ${len} },`);
  }
  lines.push("\t},");

  if (entries) {
    // Every translated page, not only the voiced ones: a page found is also a page the
    // addon does not ask the player to contribute, and it falls back per page to another
    // language's clip like any other.
    lines.push("", ...indexLua(pageIndex(entries)));
  }

  lines.push(
    "}",
    "",
    "SpokenBooksAudioPacks = SpokenBooksAudioPacks or {}",
    "SpokenBooksAudioPacks[ADDON_NAME] = pack",
    "",
  );
  return lines.join("\n");
}

/**
 * Writes Data/Sounds.lua from the current takes. Returns what it wrote.
 *
 * @param options.lang which language's takes, defaulting to English
 * @param options.out an explicit path, for tests
 */
export async function buildLookup({ lang = LANG, out = lookupPath(lang) } = {}) {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set -- the takes live in Postgres");

  const pool = new pg.Pool({ connectionString: url });
  try {
    // Joined to the corpus rather than trusting the take's lineId: a take for a page no
    // longer in the corpus has nothing to narrate, and an entry for it would be a row the
    // addon can never reach.
    const { rows } = await pool.query(
      `select b."pageId", t."file", t."durationSec"
         from "take" t
         join "book_line" b
           on b."lineId" = t."lineId" and b."lang" = t."lang" and b."isCurrent"
        where t."source" = 'books' and t."isCurrent" and t."lang" = $1
        order by b."pageId"`,
      [lang],
    );

    let entries = null;
    if (lang !== LANG) {
      // The newest extracted version, not the live row: the client shows the world
      // database's words, and a correction made here changes what is voiced, not what is on
      // screen. Placed by the English page, which is what fixes a page's book and number.
      const pages = await pool.query(
        `select e."pageId", e."bookId", e."pageNumber", e."ownerKind", e."ownerIds", l."text"
           from (select distinct on ("lineId") "lineId", "text" from "book_line"
                  where "lang" = $1 and "origin" = 'extracted'
                  order by "lineId", "version" desc) l
           join "book_line" e on e."lineId" = l."lineId" and e."lang" = $2 and e."isCurrent"`,
        [lang, LANG],
      );
      // The same rule for the owners' names.
      const names = await pool.query(
        `select distinct on ("kind", "entityId") "kind", "entityId", "name" from "entity_name"
          where "lang" = $1 and "origin" = 'extracted' and "kind" in ('gameobject', 'item')
          order by "kind", "entityId", "version" desc`,
        [lang],
      );
      entries = localeEntries(pages.rows, names.rows);
    }

    await mkdir(dirname(out), { recursive: true });
    await writeFile(out, packLua(lang, rows, entries));

    return { clips: rows.length, pages: entries?.length ?? null, path: out };
  } finally {
    await pool.end();
  }
}
