// The corpus, as the table the addon looks a page up in.
//
// WHAT IS NOT HERE IS THE POINT: no page text. The addon has the words on screen already,
// and shipping 1.3 MB of prose a second time would make the data module the largest thing
// in the addon for no gain. What it cannot work out for itself is which page it is looking
// at and what follows it, so that is all this carries.
//
// A page is found by title, page number and a checksum of its text. Title and number alone
// are not enough: seven different books are called "Decoded Twilight Text" and each holds
// different words. The checksum alone is enough only when it is unique corpus-wide, which is
// what `loose` records -- a fallback for a client whose object name does not match ours.

import { pageChecksum } from "./naming.mjs";

/** Lua's quoting rules, for the two characters a WoW object name can actually contain. */
function quote(text) {
  return `"${String(text).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

const HEADER = `-- AUTO-GENERATED by pipelines/books/tools/export.mjs. Do not edit by hand.
--
-- The corpus is the "book_line" table on the site; this file is an export of it, committed
-- so the addon builds on a clone with no database. Regenerate with:  make books-export
--
-- No page text. The addon reads the words off the screen it is narrating; what it cannot
-- know is which page those words are, which is what the checksums below answer.
--
-- A global rather than a private namespace, as the zones data files are: a data file
-- cannot reach into the addon's environment.
`;

/**
 * The two tables a page is found by, in the shape the addon's Reader reads.
 *
 * @param entries rows of pageId, bookId, pageNumber, text and either title or titles: a
 *   translated page is listed under each name its owners have in that language, and one
 *   whose owners have none is reachable only through `loose`
 * @returns index (title -> page number -> checksum -> pageId) and loose ([checksum, pageId]
 *   for checksums no other page shares)
 */
export function pageIndex(entries) {
  const sorted = [...entries].sort((a, b) => a.bookId - b.bookId || a.pageNumber - b.pageNumber);
  const checksums = new Map(sorted.map((entry) => [entry.pageId, pageChecksum(entry.text)]));

  const index = new Map();
  for (const entry of sorted) {
    for (const title of entry.titles ?? [entry.title]) {
      if (!index.has(title)) index.set(title, new Map());
      const byNumber = index.get(title);
      if (!byNumber.has(entry.pageNumber)) byNumber.set(entry.pageNumber, new Map());
      const byChecksum = byNumber.get(entry.pageNumber);
      const sum = checksums.get(entry.pageId);
      // First writer wins, and the rows arrive sorted, so the lowest book keeps the slot.
      // Four books are called "Inscribed Kodo Leather" and hold identical text: nothing on
      // screen distinguishes them, so the addon cannot either and the narration is the same
      // either way. Overwriting instead would make the answer depend on row order, which is
      // the kind of thing that changes under a re-extract and moves audio for no reason.
      if (!byChecksum.has(sum)) byChecksum.set(sum, entry.pageId);
    }
  }

  // An ambiguous checksum is dropped rather than resolved by order: guessing here narrates
  // the wrong page's words.
  const seen = new Map();
  for (const entry of sorted) {
    const sum = checksums.get(entry.pageId);
    seen.set(sum, seen.has(sum) && seen.get(sum) !== entry.pageId ? null : entry.pageId);
  }
  const loose = [...seen.entries()].filter(([, pageId]) => pageId !== null);

  return { index, loose };
}

/** `index = {...}` and `loose = {...}`, one tab in, as fields of a table literal. */
export function indexLua({ index, loose }) {
  const lines = ["\tindex = {"];
  for (const title of [...index.keys()].sort()) {
    lines.push(`\t\t[${quote(title)}] = {`);
    for (const number of [...index.get(title).keys()].sort((a, b) => a - b)) {
      const byChecksum = index.get(title).get(number);
      const pairs = [...byChecksum.entries()]
        .sort(([a], [b]) => a - b)
        .map(([sum, pageId]) => `[${sum}] = ${pageId}`);
      lines.push(`\t\t\t[${number}] = { ${pairs.join(", ")} },`);
    }
    lines.push("\t\t},");
  }

  lines.push("\t},", "", "\tloose = {");
  for (const [sum, pageId] of [...loose].sort(([a], [b]) => a - b)) {
    lines.push(`\t\t[${sum}] = ${pageId},`);
  }
  lines.push("\t},");
  return lines;
}

/**
 * @param entries corpus rows: pageId, bookId, pageNumber, pageCount, title, text
 */
export function booksLua(entries) {
  // Sorted throughout, so re-exporting an unchanged corpus produces an identical file and a
  // diff shows only what actually moved.
  const sorted = [...entries].sort((a, b) => a.bookId - b.bookId || a.pageNumber - b.pageNumber);

  const books = new Map();
  for (const entry of sorted) {
    if (!books.has(entry.bookId)) books.set(entry.bookId, { title: entry.title, pages: [] });
    books.get(entry.bookId).pages.push(entry.pageId);
  }

  const lines = [HEADER, "SpokenBooksData = {", "\tversion = 1,", "", ...indexLua(pageIndex(sorted))];

  lines.push("", "\tpages = {");
  for (const entry of [...sorted].sort((a, b) => a.pageId - b.pageId)) {
    lines.push(`\t\t[${entry.pageId}] = { book = ${entry.bookId}, number = ${entry.pageNumber} },`);
  }

  lines.push("\t},", "", "\tbooks = {");
  for (const bookId of [...books.keys()].sort((a, b) => a - b)) {
    const book = books.get(bookId);
    lines.push(`\t\t[${bookId}] = { title = ${quote(book.title)}, pages = { ${book.pages.join(", ")} } },`);
  }

  lines.push("\t},", "}", "");
  return lines.join("\n");
}
