#!/usr/bin/env node
// Writes addon/SpokenZones/Data/<locale>/Aliases.lua for every non-English locale.
//
//   node tools/locale/build-aliases.mjs               # pinned build
//   node tools/locale/build-aliases.mjs --build 1.15.9.69109
//
// The corpus is keyed by English area name in every language, because a place is
// one place whatever it is called. The client, however, hands the addon the name
// in its own language: a German client reports "Sengende Schlucht", which
// matches nothing, which is why non-English players saw no subzone lore at all
// before these tables existed. AreaTable carries both names against one ID, so
// the mapping is a join, not a translation, and costs nothing to produce.
//
// Keyed by the RAW client name rather than a normalised one. SpokenZones's
// normalisation reduces a name to [a-z0-9 ] to reconcile the wiki's punctuation
// with the client's, and that is exactly wrong here: "Дун Морог" normalises to
// nothing at all. AreaTable is the table the client reads its names out of, so
// an exact string match is both available and the most precise thing on offer.
//
// Some locales have no Era translation and their table comes out empty. That is
// a real answer -- Italian Classic runs on English area names -- not a failure.
//
// It also writes tools/seed/area-names.json: every corpus zone and subzone's name in
// each language, same-as-English ones included, zones from UiMap and subzones from
// AreaTable. That is what the site names places with (tools/lore/import-names.mjs); the
// alias tables cannot serve for it, see lib/area-names.mjs. The Era build names what it
// has, and the Camelot build (seed/camelot-areas.json) fills in the places only it has
// -- Mount Hyjal, the Darkspear Islands -- which Era's tables have no row for.

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { areaNames, mapNames } from "../lib/area-names.mjs";
import { fetchTable, PINNED_BUILD } from "../lib/db2.mjs";
import { BASE_LOCALE, LOCALES } from "../lib/locales.mjs";
import { readSubzones, readZones } from "../lib/loredata.mjs";
import { luaString, normaliseKey, readJson, ROOT } from "../lib/wiki.mjs";

const SEED = join(ROOT, "pipelines/zones/tools/seed/area-names.json");

const argv = process.argv.slice(2);
const build = argv.includes("--build") ? argv[argv.indexOf("--build") + 1] : PINNED_BUILD;

function emitAliases(locale, aliases, build) {
  const lines = [
    "-- AUTO-GENERATED by tools/locale/build-aliases.mjs. Do not edit by hand.",
    "--",
    `-- Area names as a ${locale} client reports them, mapped to the English keys the`,
    "-- corpus is stored under. Built by joining AreaTable's localized and English",
    `-- strings on their shared ID, from client build ${build}.`,
    "--",
    "-- Keyed by the raw client name: SpokenZones:NormaliseAreaKey reduces a name to",
    "-- [a-z0-9 ], which erases a Cyrillic or Chinese name entirely.",
    "",
    "local _, SpokenZones = ...",
    "",
    `if not SpokenZones:ShouldLoadAliases("${locale}") then`,
    "\treturn",
    "end",
    "",
    "local aliases = {",
  ];

  for (const name of [...aliases.keys()].sort()) {
    lines.push(`\t[${luaString(name)}] = ${luaString(aliases.get(name))},`);
  }

  lines.push("}", "", `SpokenZones:RegisterAliases("${locale}", aliases)`, "");
  return lines.join("\n");
}

async function main() {
  // Only names the corpus actually has lore for. AreaTable is four times the
  // size of the corpus, and an alias to a key nothing is stored under is weight
  // in every player's memory for no lookup that can ever succeed.
  const subzones = await readSubzones();
  const wanted = new Set(subzones.map((s) => s.key));

  console.log(`fetching AreaTable for ${build}`);
  const english = await fetchTable("AreaTable", { build });
  const mapIDs = new Set((await readZones()).map((z) => z.mapID));
  const camelot = (await readJson(join(ROOT, "pipelines/zones/tools/seed/camelot-areas.json"))).build;
  console.log(`fetching AreaTable for ${camelot}`);
  const camelotEnglish = await fetchTable("AreaTable", { build: camelot });
  const seed = {};
  const englishById = new Map(english.map((row) => [row.ID, (row.AreaName_lang || "").trim()]));

  for (const locale of LOCALES) {
    if (locale.code === BASE_LOCALE) continue;

    const rows = await fetchTable("AreaTable", { build, locale: locale.code });
    const maps = await fetchTable("UiMap", { build, locale: locale.code });
    const [camelotRows, camelotMaps] = await Promise.all([
      fetchTable("AreaTable", { build: camelot, locale: locale.code }),
      fetchTable("UiMap", { build: camelot, locale: locale.code }),
    ]);
    // Era first, so a name both builds carry is Era's; Camelot only adds.
    const zones = new Map([...mapNames(camelotMaps, mapIDs), ...mapNames(maps, mapIDs)]);
    const areas = new Map([
      ...areaNames(camelotEnglish, camelotRows, wanted),
      ...areaNames(english, rows, wanted),
    ]);
    seed[locale.code] = {
      zones: Object.fromEntries([...zones].sort(([a], [b]) => a - b)),
      subzones: Object.fromEntries([...areas].sort(([a], [b]) => (a < b ? -1 : 1))),
    };

    const aliases = new Map();
    // A localized name that stands for two different English keys cannot be
    // resolved from the name alone, so neither reading is stored: a wrong alias
    // shows the wrong lore, which is worse than the miss it replaces.
    const ambiguous = new Set();
    // Key -> localized name. Several AreaTable rows can share one English name
    // (a zone and its like-named area, an instance entrance); the first localized
    // name wins, and a later different one is left -- they are the same place with
    // the same name in practice, and a disagreement is a data curiosity, not a
    // second name for the explorer to pick between.

    for (const row of rows) {
      const localized = (row.AreaName_lang || "").trim();
      const englishName = englishById.get(row.ID);
      if (!localized || !englishName) continue;

      const key = normaliseKey(englishName);
      if (localized === englishName) continue;
      if (!wanted.has(key)) continue;

      const existing = aliases.get(localized);
      if (existing && existing !== key) {
        ambiguous.add(localized);
        aliases.delete(localized);
      } else if (!ambiguous.has(localized)) {
        aliases.set(localized, key);
      }
    }

    const dir = join(ROOT, "addons/SpokenZones/Data", locale.code);
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, "Aliases.lua"), emitAliases(locale.code, aliases, build));

    // Coverage counts corpus keys reached, not alias rows: several client names
    // can share one key, and counting rows reports more than 100% coverage.
    // The keys with no alias are the ones whose name is the same in both
    // languages -- harmless on a Latin client, which normalises its way to them,
    // and unreachable on one whose script normalisation erases.
    const covered = new Set(aliases.values()).size;
    const pct = ((covered / wanted.size) * 100).toFixed(0);
    const note = ambiguous.size ? `, ${ambiguous.size} ambiguous dropped` : "";
    console.log(
      `${locale.code}: ${covered} of ${wanted.size} subzone keys (${pct}%) via ${aliases.size} names${note}`,
    );
  }

  const out = {
    _comment: [
      "What each corpus zone and subzone is called in each client language, from the",
      "client's own tables via wago.tools: zones from UiMap by uiMapID, subzones from",
      "AreaTable by English key, the Era build first and the Camelot build for places",
      "only it has. Names the same as English are kept: they are that language's",
      "name too. Read by tools/lore/import-names.mjs.",
      "Regenerate with:  make zones-aliases",
    ],
    builds: [build, camelot],
    names: seed,
  };
  await writeFile(SEED, JSON.stringify(out, null, 2) + "\n");
  console.log(`wrote ${SEED}`);

}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
