#!/usr/bin/env node
//
// manifest.json -> addon/<pack folder>/Data/Sounds.lua
//
// Run after any generation. The addon resolves every clip through this table, so
// audio that is not in it is unreachable, and a row pointing at a file that is not
// on disk plays silence.

import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { loadEnvFile } from "../lib/env.mjs";
import { close as closeStore, loadManifest, packDir, soundsDir } from "./store.mjs";

function luaString(text) {
  return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// The manifest stores a POSIX path because that is what the files on disk are.
// WoW addresses its own files with backslashes, and Audio.lua already builds the
// prefix that way, so emitting "1411/zone" here would produce
// "Interface\AddOns\ZoneLoreAudio\Sounds\1411/zone.mp3" -- a mixed-separator path
// that is not worth finding out about in-game, where it plays silence.
function luaPath(file) {
  return luaString(file.replace(/\//g, "\\"));
}

/**
 * Regenerates addon/ZoneLoreAudio/Data/Sounds.lua from the current takes.
 *
 * Exported so the web app can call it straight after a regeneration -- the addon
 * resolves every clip through this table, so a new take that is not in it is
 * unreachable and the old duration would reset the Play button at the wrong moment.
 */
export async function buildLookup() {
  const manifest = await loadManifest();

  const zones = new Map();      // mapID -> row
  const subzones = new Map();   // mapID -> Map(key -> row)
  let missingFiles = 0;

  for (const [id, record] of Object.entries(manifest)) {
    if (!existsSync(join(soundsDir(), `${record.file}.mp3`))) {
      console.warn(`warning: ${id} is in the manifest but ${record.file}.mp3 is not on disk`);
      missingFiles++;
      continue;
    }

    const [kind, mapIDText, ...rest] = id.split(":");
    const mapID = Number(mapIDText);
    const row = { file: record.file, len: record.durationSec };

    if (kind === "z") {
      zones.set(mapID, row);
    } else if (kind === "s") {
      // Rejoin: a canonical key never contains a colon, but splitting on one and
      // taking [2] would quietly truncate it if that ever stopped being true.
      const key = rest.join(":");
      if (!subzones.has(mapID)) subzones.set(mapID, new Map());
      subzones.get(mapID).set(key, row);
    } else {
      throw new Error(`unknown lineId kind in ${id}`);
    }
  }

  const lines = [
    "-- AUTO-GENERATED by tools/voice/build-lookup.mjs. Do not edit by hand.",
    "--",
    "-- Durations are recorded at generation time because the client cannot report",
    "-- how long a sound file is; without them the Play button never resets itself.",
    "--",
    "-- Globals rather than a private namespace: a data addon cannot reach into",
    "-- SpokenZones's, which is how AI_VoiceOverData_Vanilla does the same job.",
    "",
    "local ADDON_NAME = ...",
    "",
    "local pack = {",
    // Bumped only when the shape below changes in a way SpokenZones cannot read.
    // Audio.lua refuses a pack whose format it does not know rather than playing
    // silence, so this is the compatibility contract between the two addons.
    "\tversion = 1,",
    "\tzones = {",
  ];

  for (const mapID of [...zones.keys()].sort((a, b) => a - b)) {
    const row = zones.get(mapID);
    lines.push(`\t\t[${mapID}] = { file = ${luaPath(row.file)}, len = ${row.len} },`);
  }

  lines.push("\t},", "\tsubzones = {");

  for (const mapID of [...subzones.keys()].sort((a, b) => a - b)) {
    lines.push(`\t\t[${mapID}] = {`);
    const table = subzones.get(mapID);
    for (const key of [...table.keys()].sort()) {
      const row = table.get(key);
      lines.push(`\t\t\t[${luaString(key)}] = { file = ${luaPath(row.file)}, len = ${row.len} },`);
    }
    lines.push("\t\t},");
  }

  lines.push(
    "\t},",
    "}",
    "",
    "-- C_AddOns is the modern home of GetAddOnMetadata and the global is the older",
    "-- one. A pack that reads only through C_AddOns errors at load on any client",
    "-- that predates it, and a shipped pack cannot be fixed retroactively.",
    "local GetAddOnMeta = (C_AddOns and C_AddOns.GetAddOnMetadata) or GetAddOnMetadata",
    "",
    "-- The folder name comes from the loader rather than being baked in, so one",
    "-- generated file serves every pack built from this tree: the English pack and a",
    "-- language's ship the same Sounds.lua and differ only in their .toc and their mp3s.",
    "pack.addon = ADDON_NAME",
    'pack.quality = GetAddOnMeta(ADDON_NAME, "X-SpokenZones-Quality") or "standard"',
    'pack.bitrate = tonumber(GetAddOnMeta(ADDON_NAME, "X-SpokenZones-Bitrate")) or 0',
    'pack.packVersion = GetAddOnMeta(ADDON_NAME, "Version") or "dev"',
    "",
    "-- Defaulted rather than required: the two packs published before languages",
    "-- existed carry no such key, and they are English.",
    'pack.language = GetAddOnMeta(ADDON_NAME, "X-SpokenZones-Language") or "enUS"',
    "",
    "-- Keyed by folder name so two packs installed at once both register instead of",
    "-- the second silently overwriting the first. Spoken Zones picks between them.",
    "--",
    "-- ONE REGISTRY. A pack built before the rename writes ZoneLoreAudioPacks, and Audio.lua",
    "-- still reads that: those files are on players' disks and cannot be changed. This is the",
    "-- other direction -- a pack this new beside an addon too old to read this name -- and it",
    "-- is not carried, because the addon and its pack are released together.",
    "SpokenZonesAudioPacks = SpokenZonesAudioPacks or {}",
    "SpokenZonesAudioPacks[ADDON_NAME] = pack",
    "",
  );

  const outPath = join(packDir(), "Data/Sounds.lua");
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, lines.join("\n"));

  const subzoneCount = [...subzones.values()].reduce((n, t) => n + t.size, 0);
  return {
    zones: zones.size,
    subzones: subzoneCount,
    zonesWithSubzones: subzones.size,
    missingFiles,
    path: outPath,
  };
}

async function main() {
  const result = await buildLookup();
  console.log(`wrote ${result.path}`);
  console.log(
    `  ${result.zones} zones, ${result.subzones} subzones across ${result.zonesWithSubzones} zones`,
  );
  if (result.missingFiles) {
    console.log(`  ${result.missingFiles} manifest entries skipped: no file on disk`);
    process.exitCode = 1;
  }
}

// Only when run as a script: buildLookup is imported by the web app, and a module
// that runs a CLI on import would run it there too.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  // .env bridged in the CLI guard only; the explorer imports this module.
  loadEnvFile()
    .then(main)
    .catch((err) => {
      console.error(`error: ${err.message}`);
      process.exitCode = 1;
    })
    .finally(() => closeStore());
}
